#!/bin/bash


###################                                  
  ###### Setting and defining baseline or config supplied variables ######
                                                         ###################  


NOW=$(date +"%m-%d-%Y %H:%M")
HISTFILE=~/Dropbox/Apps/.notesourcehistory
NOTESTORAGE=~/Dropbox/Apps/research.txt

# load history from HISTFILE into program for use
history -r

###################  
  #####  'Source' variable  -- static --   #####
                               ###################  

echo "What's your Source? "
echo ""
read -ep "for previous entries, use the up arrow:  " source
history -s "$source"

echo "   "

#search for the source in the HISTFILE. if no match is found (new source), save to HISTFILE
h=$(grep -c "$source" "$HISTFILE")

tput setb [3]

if [ "$h" == 0 ]
	then 
	  echo "$source">>$HISTFILE
	  echo "+++++ New source Saved +++++"
	  echo ""
	  echo ""
else
history -c
	  fi

###################  
  #### 'Body' Section  -- begin extended loop until new 'source' -- ####
                                                       ###################  

tput setb [2]

while :
do
	echo "What would you like to note?"
	echo "'q' or 'quit' to exit"
	echo ""
	read -e body
	if [ "${body,,}" = "quit" -o "q" ]
	then
	  break

###################  	  
  #### 'Tag' Section -- continue extended loop and initialize nested 'tag' loop ####
                                                                   ###################  
	  
# set 'tags' to tag symbol so that tags from last entry aren't appended and first tag is registered
tags= '@'

	else
				tput sc
				
				echo ""
				echo -ne "Search or enter Tags Here: "
				read taginput
				
				taginput=$(echo $taginput | tr -d ' ')
				tags=$(echo "$tags$taginput, ")
				tags=$(echo ${tags//","/" @"})
				
				
				tput cuu1
				tput cuu1
				echo ""
				echo "Tags :  $tags                  "

###################  
  #### 'Summary' section -- break from 'tag' nested loop and continue extended loop ####
                                                                       ###################                                                                  

				echo ""
				echo "Summary : "
				read summary
			
				echo ""

############################		                                      
  ######### Write Note variables to notebook plaintext file (variable NOTESTORAGE from config file) #########
                                                                                   ############################

		
		echo "$NOW   ${summary^^}" >>$NOTESTORAGE
		echo "   $body" >>$NOTESTORAGE
		echo "        ----@$tags---     $source" >>$NOTESTORAGE
		echo "   " >>$NOTESTORAGE
		echo "   " >>$NOTESTORAGE

		echo ""
		echo "+++   Noted!   +++"
		echo ""
		echo "" 
fi
done

echo ""
echo ""
echo "====== Notes Filed ======"
echo ""
echo ""
